# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyelement'),
        ('dashboard', '0004_auto_20160826_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtemplate',
            name='company_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyElement'),
            preserve_default=False,
        ),
    ]
