# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20160822_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtemplate',
            name='users',
            field=models.ManyToManyField(related_name='have_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
