# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-10 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dashboardtemplate_company_element'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='dashboardtemplate',
            name='company',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
