# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_dashboardtemplate_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtemplate',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
