# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        ('users', '0001_initial'),
        ('tenants', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='consultants',
            field=models.ManyToManyField(to='users.TenantConsultant'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='research_methodology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='projects.ResearchMethodology'),
        ),
        migrations.AddField(
            model_name='project',
            name='shoppers',
            field=models.ManyToManyField(to='users.Shopper'),
        ),
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
        ),
        migrations.AddField(
            model_name='placetoassess',
            name='place_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='content_type_place_to_assess', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='placetoassess',
            name='research_methodology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_to_assess',
                                    to='projects.ResearchMethodology'),
        ),
        migrations.AddField(
            model_name='evaluationassessmentlevel',
            name='consultants',
            field=models.ManyToManyField(to='users.TenantConsultant'),
        ),
        migrations.AddField(
            model_name='evaluationassessmentlevel',
            name='previous_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='next_level', to='projects.EvaluationAssessmentLevel'),
        ),
        migrations.AddField(
            model_name='evaluationassessmentlevel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='evaluationassessmentlevel',
            name='project_manager',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='evaluationassessmentcomment',
            name='commenter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter_type',
                                    to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='evaluationassessmentcomment',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Evaluation'),
        ),
        migrations.AddField(
            model_name='evaluationassessmentcomment',
            name='evaluation_assessment_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='projects.EvaluationAssessmentLevel'),
        ),
        migrations.AddField(
            model_name='evaluationassessmentcomment',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.Questionnaire'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='employee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='employee_type', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='entity',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_assessment_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='projects.EvaluationAssessmentLevel'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='questionnaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='evaluation', to='questionnaires.Questionnaire'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='questionnaire_script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='questionnaires.QuestionnaireScript'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='questionnaire_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='questionnaires.QuestionnaireTemplate'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='section',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='shopper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Shopper'),
        ),
    ]
