# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        ('projects', '0002_auto_20160531_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationassessmentcomment',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.QuestionnaireQuestion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='shoppers',
            field=models.ManyToManyField(blank=True, to='users.Shopper'),
        ),
    ]
