# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_evaluation_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='visit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
