# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_evaluation_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='saved_by_user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='shopper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Shopper'),
        ),
    ]
