# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 14:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160909_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='graph_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
