# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyelement'),
        ('projects', '0006_project_graph_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='company_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='companies.CompanyElement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='company_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.CompanyElement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchmethodology',
            name='company_elements',
            field=models.ManyToManyField(related_name='research_methodologies', to='companies.CompanyElement'),
        ),
    ]
