# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 15:51
from __future__ import unicode_literals

from django.contrib.contenttypes.models import ContentType
from django.db import migrations, connection

from mystery_shopping.companies.models import CompanyElement
from mystery_shopping.projects.models import ResearchMethodology, Project, Evaluation


class ResearchMethodologyReassign:
    def __init__(self, research_methodology):
        self.research_methodology = research_methodology
        self.reassign()

    def add_section_to_research_methodology(self, place_to_assess):
        try:
            company_element = CompanyElement.objects.get(additional_info__old_section_id=place_to_assess.place_id)
            self.research_methodology.company_elements.add(company_element)
        except:
            pass

    def add_entity_to_research_methodology(self, place_to_assess):
        try:
            company_element = CompanyElement.objects.get(additional_info__old_entity_id=place_to_assess.place_id)
            self.research_methodology.company_elements.add(company_element)
        except:
            pass

    def add_department_to_research_methodology(self, place_to_assess):
        try:
            company_element = CompanyElement.objects.get(additional_info__old_department_id=place_to_assess.place_id)
            self.research_methodology.company_elements.add(company_element)
        except:
            pass

    def reassign(self):
        for place_to_assess in self.research_methodology.places_to_assess.all():
            if place_to_assess.place_type.model_class() == ContentType(app_label='companies', model='section').model_class():
                self.add_section_to_research_methodology(place_to_assess)
            elif place_to_assess.place_type.model_class() == ContentType(app_label='companies', model='entity').model_class():
                self.add_entity_to_research_methodology(place_to_assess)
            elif place_to_assess.place_type.model_class() == ContentType(app_label='companies', model='department').model_class():
                self.add_department_to_research_methodology(place_to_assess)


class EvaluationReassignCompanyElement:
    def __init__(self, evaluation):
        self.evaluation = evaluation
        self.reassign()

    def set_section(self, section_id):
        company_element = CompanyElement.objects.get(additional_info__old_section_id=section_id)
        self.evaluation.company_element = company_element
        self.evaluation.save()

    def set_entity(self, entity_id):
        company_element = CompanyElement.objects.get(additional_info__old_entity_id=entity_id)
        self.evaluation.company_element = company_element
        self.evaluation.save()

    def reassign(self):
        with connection.cursor() as cursor:
            cursor.execute("select section_id, entity_id from projects_evaluation where id = %s", [self.evaluation.pk])
            row = cursor.fetchone()

        if row[0] is not None:
            self.set_section(row[0])
        elif row[1] is not None:
            self.set_entity(row[1])


def migrate_research_methodologies():
    research_methodologies = ResearchMethodology.objects.all()
    for research_methodology in research_methodologies:
        ResearchMethodologyReassign(research_methodology)


def migrate_projects():
    with connection.cursor() as cursor:
        cursor.execute('''
                UPDATE projects_project AS p SET company_new_id =
                  (SELECT c.id FROM companies_companyelement AS c
                  WHERE c.additional_info -> 'old_company_id' = p.company_id::TEXT);
                ''')


def migrate_evaluations():
    evaluations = Evaluation.objects.all()
    for evaluation in evaluations:
        EvaluationReassignCompanyElement(evaluation)


def migrate_all(*args):
    migrate_research_methodologies()
    migrate_projects()
    migrate_evaluations()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20161230_1529'),
    ]

    operations = [
        migrations.RunPython(migrate_all)
    ]
