# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170102_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchmethodology',
            name='number_of_evaluations',
            field=models.PositiveIntegerField(),
        ),
    ]
