# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_auto_20170102_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='shopper_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationassessmentcomment',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_assessment_comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationassessmentlevel',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='evaluation_assessment_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='consultants_new',
            field=models.ManyToManyField(blank=True, related_name='consultant_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager_new',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='manager_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='shoppers_new',
            field=models.ManyToManyField(blank=True, related_name='shopper_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='saved_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_evaluations', to=settings.AUTH_USER_MODEL),
        ),
    ]
