# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 14:34
from __future__ import unicode_literals

from django.db import migrations

from mystery_shopping.projects.models import Project, Evaluation


class MigrateProject:
    def __init__(self, project):
        self.project = project
        self.update_object()

    def update_object(self):
        self.project.project_manager_new = self.project.project_manager.user
        self.project.save()

        for consultant in self.project.consultants.all():
            self.project.consultants_new.add(consultant.user)

        for shopper in self.project.shoppers.all():
            self.project.shoppers_new.add(shopper.user)


class MigrateEvaluation:
    def __init__(self, evaluation):
        self.evaluation = evaluation
        self.update_object()

    def update_object(self):
        if self.evaluation.shopper is not None:
            self.evaluation.shopper_new = self.evaluation.shopper.user
            self.evaluation.save()


def migrate_projects():
    projects = Project.objects.all()
    for project in projects:
        MigrateProject(project)


def migrate_evaluations():
    evaluations = Evaluation.objects.all()
    for evaluation in evaluations:
        MigrateEvaluation(evaluation)


def migrate_all(*args):
    migrate_projects()
    migrate_evaluations()



class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170106_1411'),
    ]

    operations = [
        migrations.RunPython(migrate_all)
    ]
