# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 14:34
from __future__ import unicode_literals

from django.db import migrations, connection

from mystery_shopping.projects.models import Project, Evaluation


def migrate_projects():
    with connection.cursor() as cursor:
        cursor.execute('''
                UPDATE projects_project AS p SET project_manager_new_id =
                  (SELECT u.user_id FROM users_tenantprojectmanager AS u WHERE u.id = p.project_manager_id);
                ''')
        cursor.execute('''
                INSERT INTO projects_project_consultants_new (project_id, user_id)
                (SELECT p.project_id, t.user_id FROM projects_project_consultants as p
                  JOIN users_tenantconsultant as t ON p.tenantconsultant_id = t.id )
            ''')
        cursor.execute('''
                INSERT INTO projects_project_shoppers_new (project_id, user_id)
                (SELECT p.project_id, s.user_id FROM projects_project_shoppers as p
                  JOIN users_shopper as s ON p.shopper_id = s.id )
            ''')


class MigrateEvaluation:
    def __init__(self, evaluation):
        self.evaluation = evaluation
        self.update_object()

    def update_object(self):
        if self.evaluation.shopper is not None:
            self.evaluation.shopper_new = self.evaluation.shopper.user
            self.evaluation.save()


def migrate_evaluations():
    with connection.cursor() as cursor:
        cursor.execute('''
                UPDATE projects_evaluation AS pe SET shopper_new_id =
                  (SELECT u.user_id FROM users_shopper AS u WHERE u.id = pe.shopper_id);
                ''')


def migrate_all(*args):
    migrate_projects()
    migrate_evaluations()



class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170106_1411'),
    ]

    operations = [
        # migrations.RunPython(migrate_all)
    ]
