# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20170106_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='section',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='shopper',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='evaluationassessmentcomment',
            name='commenter_id',
        ),
        migrations.RemoveField(
            model_name='evaluationassessmentcomment',
            name='commenter_type',
        ),
        migrations.RemoveField(
            model_name='evaluationassessmentlevel',
            name='consultants',
        ),
        migrations.RemoveField(
            model_name='evaluationassessmentlevel',
            name='project_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.RemoveField(
            model_name='project',
            name='graph_config',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='shoppers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='consultants',
        ),
    ]
