# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170107_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='shopper_new',
            new_name='shopper',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='company_new',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='consultants_new',
            new_name='consultants',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_manager_new',
            new_name='project_manager',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='shoppers_new',
            new_name='shoppers',
        ),
    ]
