# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20170107_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Project Name', max_length=150),
            preserve_default=False,
        ),
    ]
