# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-02 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0014_auto_20170329_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detractors_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detractors_manager_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
