# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-14 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_detractors_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placetoassess',
            name='place_type',
        ),
        migrations.RemoveField(
            model_name='placetoassess',
            name='research_methodology',
        ),
        migrations.DeleteModel(
            name='PlaceToAssess',
        ),
    ]
