# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_subindustry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subindustry',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subindustry', to='companies.Industry'),
        ),
        migrations.AlterField(
            model_name='subindustry',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
