# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20160913_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
