# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 16:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields

from mystery_shopping.companies.models import Company, CompanyElement


def migrate_companies(*args):
    """asdasd"""


class Migration(migrations.Migration):
    dependencies = [
        ('companies', '0006_company_subindustry'),
    ]

    operations = [
        HStoreExtension(),

        migrations.CreateModel(
            name='CompanyElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=100)),
                ('element_type', models.CharField(max_length=100)),
                ('additional_info', django.contrib.postgres.fields.hstore.HStoreField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='children', to='companies.CompanyElement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_companies)
    ]
