# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 14:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyelement',
            name='additional_info',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True),
        ),
    ]
