# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('companies', '0007_companyelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('input_type', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant')),
            ],
        ),
    ]
