# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20170103_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfotype',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
            preserve_default=False,
        ),
    ]
