# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 12:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20170105_1010'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companyelement',
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
    ]
