# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20170117_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyelement',
            options={'permissions': (('manager_companyelement', 'Manager of company element'), ('view_detractors_for_companyelement', 'View detractors for company element'), ('view_statistics_for_companyelement', 'View statistics for company element'), ('view_coded_causes_for_companyelement', 'View detractors for company element'))},
        ),
    ]
