# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-10 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_auto_20171010_1623'),
        ('cxi', '0010_auto_20171010_1623'),
        ('companies', '0012_auto_20170118_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
