# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_questionnairetemplate_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossindex',
            old_name='cross_index_template',
            new_name='template_cross_indexes',
        ),
        migrations.RenameField(
            model_name='crossindexquestiontemplate',
            old_name='cross_index_template',
            new_name='template_cross_indexes',
        ),
        migrations.RenameField(
            model_name='crossindextemplate',
            old_name='question_templates',
            new_name='template_questions',
        ),
    ]
