# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20160809_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossindex',
            old_name='template_cross_indexes',
            new_name='template_cross_index',
        ),
        migrations.RenameField(
            model_name='crossindexquestiontemplate',
            old_name='template_cross_indexes',
            new_name='template_cross_index',
        ),
    ]
