# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20160811_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossindexquestiontemplate',
            old_name='question_template',
            new_name='template_question',
        ),
    ]
