# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_auto_20160824_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairequestion',
            name='additional_info',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='questionnairetemplatequestion',
            name='additional_info',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
