# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_auto_20160901_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairequestion',
            name='question_body',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='questionnairetemplatequestion',
            name='question_body',
            field=models.CharField(max_length=400),
        ),
    ]
