# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_auto_20160915_1314'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questionnaireblock',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='questionnairetemplateblock',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='crossindexquestion',
            name='cross_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_index_questions', to='questionnaires.CrossIndex'),
        ),
        migrations.AlterField(
            model_name='crossindexquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_index_questions', to='questionnaires.QuestionnaireQuestion'),
        ),
        migrations.AlterField(
            model_name='crossindexquestiontemplate',
            name='template_cross_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_index_template_questions', to='questionnaires.CrossIndexTemplate'),
        ),
        migrations.AlterField(
            model_name='crossindexquestiontemplate',
            name='template_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_index_template_questions', to='questionnaires.QuestionnaireTemplateQuestion'),
        ),
        migrations.AlterField(
            model_name='crossindextemplate',
            name='questionnaire_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_cross_indexes', to='questionnaires.QuestionnaireTemplate'),
        ),
        migrations.AlterField(
            model_name='crossindextemplate',
            name='template_questions',
            field=models.ManyToManyField(related_name='template_cross_indexes', through='questionnaires.CrossIndexQuestionTemplate', to='questionnaires.QuestionnaireTemplateQuestion'),
        ),
    ]
