# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:11
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_merge'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questionnaireblock',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='questionnairetemplateblock',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
