# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_auto_20160416_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireblock',
            name='template_block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='questionnaires.QuestionnaireTemplateBlock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnairequestion',
            name='template_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.QuestionnaireTemplateQuestion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crossindex',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
