# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('questionnaires', '0009_auto_20161222_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairequestion',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnairetemplatequestion',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questionnairetemplatequestion',
            name='allow_why_causes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionnairetemplatequestion',
            name='has_other_choice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionnairetemplatequestion',
            name='new_algorithm',
            field=models.BooleanField(default=True),
        ),

    ]
