# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_auto_20160416_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossindex',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
