# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import mystery_shopping.tenants.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_auto_20160426_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairequestion',
            name='additional_info',
            field=models.CharField(blank=mystery_shopping.tenants.models.Tenant, max_length=30),
        ),
        migrations.AddField(
            model_name='questionnairetemplatequestion',
            name='additional_info',
            field=models.CharField(blank=mystery_shopping.tenants.models.Tenant, max_length=30),
        ),
        migrations.AlterField(
            model_name='questionnairequestion',
            name='type',
            field=models.CharField(choices=[('t', 'Text Field'), ('d', 'Date Field'), ('s', 'Single Choice'), ('m', 'Multiple Choice'), ('i', 'Indicator Question')], default='t', max_length=1),
        ),
        migrations.AlterField(
            model_name='questionnairetemplatequestion',
            name='type',
            field=models.CharField(choices=[('t', 'Text Field'), ('d', 'Date Field'), ('s', 'Single Choice'), ('m', 'Multiple Choice'), ('i', 'Indicator Question')], default='t', max_length=1),
        ),
    ]
