# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0010_auto_20170221_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_weights', to='questionnaires.QuestionnaireTemplateQuestion')),
            ],
            options={
                'default_related_name': 'custom_weights',
            },
        ),
    ]
