# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0010_auto_20170221_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairetemplatequestion',
            name='allow_why_causes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionnairetemplatequestion',
            name='has_other_choice',
            field=models.BooleanField(default=True),
        ),
    ]
