# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0010_auto_20160429_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossIndexQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CrossIndexQuestionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='crossindex',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='crossindextemplate',
            name='question_templates',
        ),
        migrations.AddField(
            model_name='crossindexquestiontemplate',
            name='template_cross_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.CrossIndexTemplate'),
        ),
        migrations.AddField(
            model_name='crossindexquestiontemplate',
            name='template_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.QuestionnaireTemplateQuestion'),
        ),
        migrations.AddField(
            model_name='crossindexquestion',
            name='cross_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.CrossIndex'),
        ),
        migrations.AddField(
            model_name='crossindexquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.QuestionnaireQuestion'),
        ),
    ]
