# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0011_auto_20160526_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossindex',
            name='questions',
            field=models.ManyToManyField(through='questionnaires.CrossIndexQuestion', to='questionnaires.QuestionnaireQuestion'),
        ),
        migrations.AddField(
            model_name='crossindextemplate',
            name='question_templates',
            field=models.ManyToManyField(through='questionnaires.CrossIndexQuestionTemplate', to='questionnaires.QuestionnaireTemplateQuestion'),
        ),
    ]
