# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0012_auto_20170414_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairequestion',
            name='min_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairetemplatequestion',
            name='min_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
