# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0012_auto_20160526_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossindexquestiontemplate',
            old_name='template_cross_index',
            new_name='cross_index_template',
        ),
    ]
