# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-27 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0013_auto_20170712_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customweight',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
