# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0013_auto_20160527_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossindexquestiontemplate',
            old_name='template_question',
            new_name='question_template',
        ),
    ]
