# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-12 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_project_detractors_manager'),
        ('users', '0013_auto_20171012_0925')
    ]

    state_operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('surname', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.CharField(blank=True, max_length=400)),
                ('additional_comment', models.CharField(blank=True, max_length=400)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(
                    choices=[('TO_CONTACT', 'To Contact'), ('CALL_BACK', 'Call Back'), ('CONTACTED', 'Contacted')],
                    default='TO_CONTACT', max_length=11)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('evaluation',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detractors',
                                   to='projects.Evaluation')),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.CreateModel(
            name='RespondentCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('issue', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('state', django_fsm.FSMField(choices=[('ASSIGNED', 'Assigned'), ('ESCALATED', 'Escalated'), ('ANAL', 'Analysis'), ('IMPLEMENTATION', 'Implementation'), ('FOLLOW_UP', 'Follow up'), ('SOLVED', 'Solved'), ('CLOSED', 'Closed')], default='ASSIGNED', max_length=50)),
                ('follow_up_tags', models.ManyToManyField(related_name='follow_up_respondent_cases', related_query_name='follow_up_respondent_cases', to='common.Tag')),
                ('follow_up_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondent_cases_to_follow_up', related_query_name='respondent_cases_to_follow_up', to=settings.AUTH_USER_MODEL)),
                ('issue_tags', models.ManyToManyField(related_name='issue_respondent_cases', related_query_name='issue_respondent_cases', to='common.Tag')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_cases', to='respondents.Respondent')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondent_cases_responsible_for', related_query_name='respondent_cases_responsible_for', to=settings.AUTH_USER_MODEL)),
                ('solution_tags', models.ManyToManyField(related_name='solution_respondent_cases', related_query_name='solution_respondent_cases', to='common.Tag')),
            ],
            options={
                'default_related_name': 'respondent_cases',
            },
        ),
        migrations.CreateModel(
            name='RespondentCaseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('case_state', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('respondent_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='respondents.RespondentCase')),
            ],
            options={
                'get_latest_by': 'date',
                'ordering': ('date',),
            },
        ),
    ]
