# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentcase',
            name='follow_up_tags',
            field=models.ManyToManyField(blank=True, related_name='follow_up_respondent_cases', related_query_name='follow_up_respondent_cases', to='common.Tag'),
        ),
        migrations.AlterField(
            model_name='respondentcase',
            name='issue_tags',
            field=models.ManyToManyField(blank=True, related_name='issue_respondent_cases', related_query_name='issue_respondent_cases', to='common.Tag'),
        ),
        migrations.AlterField(
            model_name='respondentcase',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_cases', related_query_name='respondent_cases', to='respondents.Respondent'),
        ),
        migrations.AlterField(
            model_name='respondentcase',
            name='solution_tags',
            field=models.ManyToManyField(blank=True, related_name='solution_respondent_cases', related_query_name='solution_respondent_cases', to='common.Tag'),
        ),
        migrations.AlterField(
            model_name='respondentcase',
            name='state',
            field=django_fsm.FSMField(choices=[('INIT', 'Init'), ('ASSIGNED', 'Assigned'), ('ESCALATED', 'Escalated'), ('ANAL', 'Analysis'), ('IMPLEMENTATION', 'Implementation'), ('FOLLOW_UP', 'Follow up'), ('SOLVED', 'Solved'), ('CLOSED', 'Closed')], default='INIT', max_length=50),
        ),
    ]
