# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0002_auto_20171110_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentcase',
            name='follow_up',
            field=models.TextField(blank=True, null=True),
        ),
    ]
