# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodedCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30)),
                ('sentiment', models.CharField(choices=[('a', 'Appreciation'), ('f', 'Frustration')], default='a', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CodedCauseLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(blank=True, max_length=30)),
                ('general', models.TextField(blank=True)),
                ('dynamics', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('causes', models.TextField(blank=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Entity')),
            ],
            options={
                'default_related_name': 'project_comments',
            },
        ),
    ]
