# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('cxi', '0001_initial'),
        ('tenants', '0001_initial'),
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='codedcauselabel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
        ),
        migrations.AddField(
            model_name='codedcause',
            name='coded_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cxi.CodedCauseLabel'),
        ),
        migrations.AddField(
            model_name='codedcause',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cxi.CodedCause'),
        ),
        migrations.AddField(
            model_name='codedcause',
            name='raw_causes',
            field=models.ManyToManyField(related_name='coded_causes', to='questionnaires.QuestionnaireQuestion'),
        ),
        migrations.AddField(
            model_name='codedcause',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
        ),
    ]
