# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_auto_20160901_1345'),
        ('cxi', '0002_auto_20160531_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('is_appreciation_cause', models.NullBooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_causes', to='questionnaires.QuestionnaireQuestion')),
            ],
        ),
        migrations.AlterField(
            model_name='codedcause',
            name='raw_causes',
            field=models.ManyToManyField(blank=True, related_name='coded_causes', to='cxi.WhyCause'),
        ),
    ]
