# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxi', '0003_auto_20160902_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whycause',
            old_name='text',
            new_name='answer',
        ),
    ]
