# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160909_1817'),
        ('cxi', '0004_auto_20160908_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedcause',
            name='project',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
    ]
