# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxi', '0005_codedcause_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whycause',
            name='answer',
            field=models.CharField(max_length=400),
        ),
    ]
