# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyelement'),
        ('cxi', '0008_auto_20161018_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='company_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to='companies.CompanyElement'),
        ),
    ]
