# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-10 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxi', '0009_projectcomment_company_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcomment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='section',
        ),
    ]
