# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-11 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170721_1354'),
        ('cxi', '0009_projectcomment_company_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcomment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='section',
        ),
        migrations.AddField(
            model_name='codedcause',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, related_name='coded_causes', to='users.ClientUser'),
        ),
    ]
