# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-14 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxi', '0010_codedcause_responsible_users'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='projectcomment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='section',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
