# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0006_evaluation_type'),
        ('nps', '0004_auto_20160405_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.TextField()),
                ('dynamics', models.TextField()),
                ('details', models.TextField()),
                ('causes', models.TextField()),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Entity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'default_related_name': 'project_comments',
            },
        ),
    ]
