# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0005_projectcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='indicator',
            field=models.CharField(choices=[('n', 'NPS questions'), ('j', 'Enjoyability questions'), ('e', 'Easiness questions'), ('u', 'Usefulness questions')], default='n', max_length=1),
        ),
    ]
