# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0006_projectcomment_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='indicator',
            field=models.CharField(blank=True, choices=[('n', 'NPS questions'), ('j', 'Enjoyability questions'), ('e', 'Easiness questions'), ('u', 'Usefulness questions')], max_length=1, null=True),
        ),
    ]
