# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0007_auto_20160425_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='causes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='dynamics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='general',
            field=models.TextField(blank=True),
        ),
    ]
