# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 07:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_detractorrespondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detractorrespondent',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
