# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160916_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='detractorrespondent',
            name='comment',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
