# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160425_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmanager',
            name='has_overview_access',
            field=models.BooleanField(default=False),
        ),
    ]
