# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:58
from __future__ import unicode_literals
from django.db import models
from django.db import migrations
from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType


def create_groups(apps, schema_editor,  with_create_permissions=True):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'Tenant Consultants'),
        Group(name=u'Tenant Project Managers'),
        Group(name=u'Tenant Product Managers'),
        Group(name=u'Client Managers'),
        Group(name=u'Client Project Managers'),
        Group(name=u'Client Employees'),
        Group(name=u'collectors'),
        Group(name=u'shoppers'),
    ])


def add_permissions_to_tenant_product_managers():
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'companies')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'cxi')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'dashboard')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'projects')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'questionnaires')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'users')


def add_permissions_to_tenant_project_managers():
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'companies')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'cxi')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'dashboard')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'projects')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'questionnaires')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'users')


def add_permissions_to_tenant_consultants():
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'cxi')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'dashboard')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'questionnaires')
    add_permissions_to_group_from_whole_app('Tenant Product Managers', 'users')


def add_permissions_to_client_project_managers():
    pass


def add_permissions_to_client_managers():
    pass


def add_permissions_to_client_employees():
    pass


def migrate_all(*args):
    add_permissions_to_tenant_product_managers()
    add_permissions_to_tenant_project_managers()
    add_permissions_to_tenant_consultants()


def add_permissions_to_group_from_whole_app(group_name, app_name):
    group, created = Group.objects.get_or_create(name=group_name)
    content_types = ContentType.objects.filter(app_label=app_name)
    permissions = Permission.objects.filter(content_type__app_label=app_name, content_type__in=content_types)
    group.permissions.add(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161222_1351'),
    ]

    operations = [
        migrations.RunPython(create_groups),
        migrations.RunPython(migrate_all)
    ]
