# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from mystery_shopping.users.models import User


class ReassignTenantToUser:
    def __init__(self, user):
        self.user = user
        self.migrate_tenant()

    def migrate_tenant(self):
        if self.user.user_type_attr is not None:
            self.user.tenant = self.user.user_type_attr.tenant
            self.user.save()


def migrate_tenant_for_current_users(*args):
    for user in User.objects.all():
        if user.is_tenant_user():
            ReassignTenantToUser(user)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0006_auto_20161222_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_drivers_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_tenant_for_current_users)
    ]
