# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class SetNumberOfQuestionsToDetractor:
    def __init__(self, detractor):
        self.detractor = detractor
        self.set_number_of_questions()

    def set_number_of_questions(self):
        questions = self.detractor.get_detractor_questions()
        if questions:
            self.detractor.number_of_questions = questions.filter(score__lte=6).count()
            self.detractor.save()


def set_number_of_questions_to_detractors(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    DetractorRespondent = apps.get_model('users', 'DetractorRespondent')

    for detractor in DetractorRespondent.objects.using(db_alias).all():
        SetNumberOfQuestionsToDetractor(detractor)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_auto_20170106_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='detractorrespondent',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_number_of_questions_to_detractors)
    ]
