# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 09:03
from __future__ import unicode_literals

from django.contrib.auth.models import Group
from django.db import migrations

from mystery_shopping.users.models import User


class AssignGroupToUser:
    def __init__(self, user):
        self.user = user
        self.reassign_group()

    def reassign_group(self):
        if hasattr(self.user, 'tenantproductmanager'):
            self.user.groups.add(Group.objects.get(name='Tenant Product Managers'))
        if hasattr(self.user, 'tenantprojectmanager'):
            self.user.groups.add(Group.objects.get(name='Tenant Project Managers'))
        if hasattr(self.user, 'tenantconsultant'):
            self.user.groups.add(Group.objects.get(name='Tenant Consultants'))
        if hasattr(self.user, 'shopper'):
            self.user.groups.add(Group.objects.get(name='shoppers'))
            self.user.groups.add(Group.objects.get(name='collectors'))
        if hasattr(self.user, 'clientprojectmanager'):
            self.user.groups.add(Group.objects.get(name='Client Project Managers'))
        if hasattr(self.user, 'clientmanager'):
            self.user.groups.add(Group.objects.get(name='Client Managers'))
        if hasattr(self.user, 'clientemployee'):
            self.user.groups.add(Group.objects.get(name='Client Employees'))


def add_groups_to_existing_users(*args):
    users = User.objects.all()
    for user in users:
        AssignGroupToUser(user)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_detractorrespondent_number_of_questions'),
    ]

    operations = [
        migrations.RunPython(add_groups_to_existing_users)
    ]
