# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20170117_0813'),
        ('users', '0010_detractorrespondent_number_of_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=60)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to='companies.CompanyElement')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientemployee',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='clientmanager',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='clientprojectmanager',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='is_collector',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_drivers_license',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.AddField(
            model_name='shopper',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
