# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-21 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170117_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detractorrespondent',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='detractorrespondent',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='detractorrespondent',
            name='surname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
